/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minepop.servegame.convosync.application;

import blir.swing.quickgui.MsgBox;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Travis
 */
public class HelpGUI extends javax.swing.JFrame {

    private final URI help;
    
    /**
     * Creates new form HelpGUI
     */
    protected HelpGUI() throws URISyntaxException {
        help = new URI("https://github.com/Blir/ConvoSync/wiki");
        initComponents();
        jButton1.setText(help.toASCIIString());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ConvoSyncClient - Help");
        setResizable(false);

        jButton1.setText("https://github.com/Blir/ConvoSync/wiki");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonPressed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(help);
            } catch (IOException ex) {
                new MsgBox("ConvoSyncClient - Error", "Couldn't reach " + help + ": " + ex, false).setVisible(true);
            }
        } else {
            new MsgBox("ConvoSyncClient - Error", "Your desktop is not supported.", false).setVisible(true);
        }
    }//GEN-LAST:event_onButtonPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
