package com.minepop.servegame.convosync.application;

import blir.swing.quickgui.MsgBox;

/**
 *
 * @author Blir
 */
public class LoginGUI extends javax.swing.JFrame {

    private ConvoSyncClient client;

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI(ConvoSyncClient client) {
        super(client.toString());
        this.client = client;
        initComponents();
        jTextField1.grabFocus();
        jTextField1.setSelectionStart(0);
        jTextField1.setSelectionEnd(jTextField1.getText().length());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("IP & Port:");

        jLabel2.setText("MC User Name:");

        jLabel3.setText("CS Password:");

        jTextField1.setText("127.0.0.1:25000");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onIPAndPortEntered(evt);
            }
        });

        jTextField2.setText("xTrollx1337");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUserNameEntered(evt);
            }
        });

        jPasswordField1.setText("password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLogin(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onIPAndPortEntered(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onIPAndPortEntered
        jTextField2.grabFocus();
        jTextField2.setSelectionStart(0);
        jTextField2.setSelectionEnd(jTextField2.getText().length());
    }//GEN-LAST:event_onIPAndPortEntered

    private void onUserNameEntered(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUserNameEntered
        jPasswordField1.grabFocus();
        jPasswordField1.setSelectionStart(0);
        jPasswordField1.setSelectionEnd(jPasswordField1.getPassword().length);
    }//GEN-LAST:event_onUserNameEntered

    private void onLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLogin
        String ipAndPort = jTextField1.getText();
        String ip;
        int port = 25000;
        if (ipAndPort.contains(":")) {
            String[] ipAndPortPieces = ipAndPort.split(":");
            if (ipAndPortPieces.length > 1) {
                ip = ipAndPortPieces[0];
                try {
                    port = Integer.parseInt(ipAndPortPieces[1]);
                } catch (NumberFormatException ex) {
                    new MsgBox("ConvoSyncClient - Warning", "Invalid port.", false).setVisible(true);
                    return;
                }
            } else {
                new MsgBox("ConvoSyncClient - Warning", "Invalid format.", false).setVisible(true);
                return;
            }
        } else {
            ip = ipAndPort;
        }
        client.name = jTextField2.getText();
        if (client.connect(ip, port, String.valueOf(jPasswordField1.getPassword()))) {
            dispose();
        } else {
            new MsgBox("ConvoSyncClient - Warning", "Couldn't reach server. Press OK to retry.", new Runnable() {
                @Override
                public void run() {
                    onLogin(null);
                }
            }, false).setVisible(true);
        }
    }//GEN-LAST:event_onLogin
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
