port: 25000
ip: null
password: null
#If this many players are on the server, it will not sync chat with the other servers.
max-players: 25
#If true, players from other servers can execute commands on this server
#via /ccmd, if they have permission to.
#Careful! If you allow cross-server commands, a player that has the permission
#to use this command on another server can execute any command on this server,
#as the plugin must assume that the sender is OP.
allow-cross-server-commands: false
notif:
  #If true, player death messages will be displayed cross-server.
  player-death: false
  #If true, AFK notifications will be displayed cross-server.
  #This is experimental;
  #sometimes AFK notifications may be displayed when they shouldn't.
  afk: false
auto-reconnect:
  after-socket-close: false
  after-socket-error: true
  after-connect-fail: true
  #This is in milliseconds, so 30000 ms is 30 seconds.
  time-delay-ms: 30000