name: ConvoSync
main: com.minepop.servegame.convosync.plugin.ConvoSync
version: 1.0.4-dev2.8
author: Blir
softdepend: [Essentials]
commands:
  convosync:
    description: Used to manage the ConvoSync plugin.
    usage: §c/<command> <setip|setport|reconnect|disconnect|status|setmaxplayers|users|version> [other parameters]
    permission: convosync.convosync
    permission-message: §cYou don't have permission to use this command.
  csay:
    description: Used to chat cross-server from the console.
    usage: §c/<command> <message>
    permission: convosync.csay
    permissions-message: §cYou don't have permission to use this command.
  ctell:
    description: Used to send a private message cross-server.
    usage: §c/<command> <to> <message>
    permission: convosync.ctell
    permission-message: §cYou don't have permission to use this command.
  ccmd:
    description: Used to execute commands on another server.
    usage: §cIf the server name has a space in it, use quotes around the server name. /<command> <server name> <command name> [args] 
    permission: convosync.ccmd
    permission-message: §cYou don't have permission to use this command.
  togglecs:
    description: Toggles cross-server chat for you.
    usage: §c/<command>
    permission: convosync.togglecs
    permission-message: §cYou don't have permission to use this command.
  csregister:
    description: Registers your CS client user account.
    usage: §c/<command>
    permission: convosync.csregister
    permission-message: §cYou don't have permission to use this command.
  ctellr:
    description: Used to reply to cross-server private messages.
    usage: §c/<command> <message>
    permission: convosync.ctell
    permission-message: §cYou don't have permission to use this command.
permissions:
  convosync.*:
    children:
      convosync.convosync: true
      convosync.csay: true
      convosync.ctell: true
      convosync.ccmd: true
      convosync.togglecs: true
      convosync.csregister: true
  convosync.convosync:
    description: Allows use of the /convosync command.
  convosync.csay:
    description: Allows use of the /csay command.
  convosync.ctell:
    default: true
    description: Allows use of the /ctell command.
  convosync.ccmd:
    description: Allows use of the /ccmd command.
  convosync.togglecs:
    description: Allows use of the /togglecs command.
    default: true
  convosync.csregister:
    description: Allows use of the /csregister command.
    default: true