name: ConvoSync
main: com.minepop.servegame.convosync.ConvoSync
version: Beta 1.1
author: Blir
softdepend: [Essentials]
commands:
  convosync:
    usage: §c/<command> <setip|setport|reconnect|status> [other parameters]
    permission: convosync.convosync
    permission-message: §cYou don't have permission to use this command.
permissions:
  convosync.*:
    children:
      convosync.convosync: true
  convosync.convosync:
    description: Allows use of the /convosync command.
    